# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development: &default
  adapter: postgresql
  database: fake_amazon_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db
  port: 5432
  
test:
  <<: *default
  database: fake_amazon_test

production:
  <<: *default
  database: fake_amazon_production
